services:

  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    container_name: adminerevo
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cashflow
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/sql/data

volumes:
  db-data:
